#!/bin/bash

#SBATCH --ntasks=4
#SBATCH --nodes=1
#SBATCH --mem=94560
#SBATCH --partition=highmem
#SBATCH --job-name=obs
#SBATCH --time=10:00:00
#SBATCH --output=OBS.out
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load openmpi/4.0.5/amd
module load conda
source activate an

python watch_simdir.py

